# Copyright 2010 - 2011, 2013, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')

# The return value is the collection of files installed in the build destination.
returnValue = []

#Not currently installing the csharp samples into the distbin
#returnValue += env.Install('$UNITY_DISTDIR/samples/csharp/basic_client', env.Dir('csharp/basic_client'))
#returnValue += env.Install('$UNITY_DISTDIR/samples/csharp/basic_client-server', env.Dir('csharp/basic_client-server'))
#returnValue += env.Install('$UNITY_DISTDIR/samples/csharp/basic_server', env.Dir('csharp/basic_server'))

returnValue += env.Install('$UNITY_DISTDIR/samples', env.Dir('Unity/BasicClient'))
returnValue += env.Install('$UNITY_DISTDIR/samples', env.Dir('Unity/BasicServer'))
returnValue += env.Install('$UNITY_DISTDIR/samples', env.Dir('Unity/Chat'))

#install libraries into samples in the source and the distdir
if env['OS_GROUP'] == 'windows':
    #place alljoyn_unity.dll into the samples
    returnValue += env.Install('Unity/BasicClient/Assets/Plugins', env['ALLJOYN_UNITY_LIB'])
    returnValue += env.Install('Unity/BasicServer/Assets/Plugins', env['ALLJOYN_UNITY_LIB'])
    returnValue += env.Install('Unity/Chat/Assets/Plugins', env['ALLJOYN_UNITY_LIB'])

    #place alljoyn_c.dll into the samples
    liballjoyn_c = '$DISTDIR/c/lib/alljoyn_c.dll'
    returnValue += env.Install('Unity/BasicClient/Assets/Plugins', liballjoyn_c)
    returnValue += env.Install('Unity/BasicServer/Assets/Plugins', liballjoyn_c)
    returnValue += env.Install('Unity/Chat/Assets/Plugins', liballjoyn_c)

if env['OS'] == 'android':
    #place alljoyn_unity.dll into the samples
    returnValue += env.Install('Unity/BasicClient/Assets/Plugins', env['ALLJOYN_UNITY_LIB'])
    returnValue += env.Install('Unity/BasicServer/Assets/Plugins', env['ALLJOYN_UNITY_LIB'])
    returnValue += env.Install('Unity/Chat/Assets/Plugins', env['ALLJOYN_UNITY_LIB'])

    #place liballjoyn_c.so into the samples
    liballjoyn_c = '$DISTDIR/c/lib/liballjoyn_c.so'
    returnValue += env.Install('Unity/BasicClient/Assets/Plugins/Android', liballjoyn_c)
    returnValue += env.Install('Unity/BasicServer/Assets/Plugins/Android', liballjoyn_c)
    returnValue += env.Install('Unity/Chat/Assets/Plugins/Android', liballjoyn_c)

Return('returnValue')
