# Copyright 2010 - 2011, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')

#Not currently installing the csharp samples into the distbin
#env.Install('$UNITY_DISTDIR/samples/csharp/basic_client', env.Dir('csharp/basic_client'))
#env.Install('$UNITY_DISTDIR/samples/csharp/basic_client-server', env.Dir('csharp/basic_client-server'))
#env.Install('$UNITY_DISTDIR/samples/csharp/basic_server', env.Dir('csharp/basic_server'))

env.Install('$UNITY_DISTDIR/samples/Unity', env.Dir('Unity/BasicClient'))
env.Install('$UNITY_DISTDIR/samples/Unity', env.Dir('Unity/BasicServer'))
env.Install('$UNITY_DISTDIR/samples/Unity', env.Dir('Unity/Chat'))


#install libraries into samples in the source and the distdir
if env['OS_GROUP'] == 'windows':
    #place alljoyn_unity.dll into the samples
    env.Install('Unity/BasicClient/Assets/Plugins', env['ALLJOYN_UNITY_LIB'])
    env.Install('Unity/BasicServer/Assets/Plugins', env['ALLJOYN_UNITY_LIB'])
    env.Install('Unity/Chat/Assets/Plugins', env['ALLJOYN_UNITY_LIB'])

    #place alljoyn_c.dll into the samples
    liballjoyn_c = '$DISTDIR/lib/alljoyn_c.dll'
    env.Install('Unity/BasicClient/Assets/Plugins', liballjoyn_c)
    env.Install('Unity/BasicServer/Assets/Plugins', liballjoyn_c)
    env.Install('Unity/Chat/Assets/Plugins', liballjoyn_c)


if env['OS_GROUP'] == 'posix':
    #Install alljoyn_jar into each of the samples
    alljoyn_jar = '$DISTDIR/java/jar/alljoyn.jar'
    #TODO figure out how to obtain bundle_jar
    #bundle_jar =

if env['OS'] == 'android':
    liballjoyn_c = 'liballjoyn_c.so'
    #TODO copy android .so library files