# Copyright 2011, 2013, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

import os
Import('env')

docenv = env.Clone()
docenv['ENV']['UNITY_DISTDIR'] = str(env.Dir('$UNITY_DISTDIR'))

# The return value is the collection of files installed in the build destination.
installDocs = []

# Build docs
if env['DOCS'] == 'html':
    generateDocs = docenv.Doxygen(source=['Doxygen_html', '../src/Status.cs'], target=[Dir('tmp'),Dir('html')])
    installDocs = docenv.Install('$UNITY_DISTDIR/docs', Dir('html'))
    docenv.Clean('Doxygen_html', Dir('html'))
    docenv.Depends(installDocs, generateDocs)

Return('installDocs')
